// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../src/app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/biomedical/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/biomedical">> = Specific
  const handler = {} as typeof import("../../src/app/biomedical/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/compliance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/compliance">> = Specific
  const handler = {} as typeof import("../../src/app/compliance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/data-protection-notice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-protection-notice">> = Specific
  const handler = {} as typeof import("../../src/app/data-protection-notice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/documentation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documentation">> = Specific
  const handler = {} as typeof import("../../src/app/documentation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/earth-observation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/earth-observation">> = Specific
  const handler = {} as typeof import("../../src/app/earth-observation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/efos-framework-details/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/efos-framework-details">> = Specific
  const handler = {} as typeof import("../../src/app/efos-framework-details/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/engage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engage">> = Specific
  const handler = {} as typeof import("../../src/app/engage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/engage/request-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engage/request-access">> = Specific
  const handler = {} as typeof import("../../src/app/engage/request-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/engagement/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagement">> = Specific
  const handler = {} as typeof import("../../src/app/engagement/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/engagement/request-access/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/engagement/request-access">> = Specific
  const handler = {} as typeof import("../../src/app/engagement/request-access/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/homepage/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/homepage">> = Specific
  const handler = {} as typeof import("../../src/app/homepage/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/initiatives/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/initiatives">> = Specific
  const handler = {} as typeof import("../../src/app/initiatives/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/legal-notice/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/legal-notice">> = Specific
  const handler = {} as typeof import("../../src/app/legal-notice/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/privacy-policy/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privacy-policy">> = Specific
  const handler = {} as typeof import("../../src/app/privacy-policy/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/research/hge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research/hge">> = Specific
  const handler = {} as typeof import("../../src/app/research/hge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/research/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/research">> = Specific
  const handler = {} as typeof import("../../src/app/research/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/resources/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/resources">> = Specific
  const handler = {} as typeof import("../../src/app/resources/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/security/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/security">> = Specific
  const handler = {} as typeof import("../../src/app/security/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/systems/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/systems">> = Specific
  const handler = {} as typeof import("../../src/app/systems/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/technical-papers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/technical-papers">> = Specific
  const handler = {} as typeof import("../../src/app/technical-papers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/terms-of-service/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/terms-of-service">> = Specific
  const handler = {} as typeof import("../../src/app/terms-of-service/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/updates/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/updates">> = Specific
  const handler = {} as typeof import("../../src/app/updates/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/validation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/validation">> = Specific
  const handler = {} as typeof import("../../src/app/validation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/send-form/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/send-form">> = Specific
  const handler = {} as typeof import("../../src/app/api/send-form/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/feed.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/feed.xml">> = Specific
  const handler = {} as typeof import("../../src/app/feed.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
